<a href="https://colab.research.google.com/github/kulvanth5/Applied-Linear-Algebra/blob/main/Eigen_values%26vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from numpy import linalg as la

n = int(input('Enter the size of the matrix'))

print('Enter the rows ')

rows = list(map(float,input().split()))

matrix = np.array(rows).reshape(n,n)

matrix

Enter the size of the matrix3
Enter the rows 
-2 5 7 0.5 -7 0 1 -1 0


array([[-2. ,  5. ,  7. ],
       [ 0.5, -7. ,  0. ],
       [ 1. , -1. ,  0. ]])

In [3]:
eval , ev = la.eig(matrix)

eval , ev

(array([ 1.85085015, -3.22271319, -7.62813696]),
 array([[-0.88979207, -0.95782492,  0.76944529],
        [-0.05026591, -0.12678742, -0.61248211],
        [-0.45358948,  0.2578689 , -0.18116185]]))

In [26]:
m = int(input('Enter no.of rows'))
n = int(input('Enter no.of columns'))

print('Enter the rows')

rows = list(map(float,input().split()))

matrix = np.array(rows).reshape(m,n)

matrix

Enter no.of rows2
Enter no.of columns4
Enter the rows
1 0 1 0 0 1 0 1


array([[1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [34]:
U , S , VT = la.svd(matrix)

sigma = np.diag(S)

Uk = U[:,:m]

Sk = sigma[:m,:m]

VTk = VT[:m,:]

np.dot(Uk,np.dot(Sk,VTk)) , matrix

(array([[1., 0., 1., 0.],
        [0., 1., 0., 1.]]),
 array([[1., 0., 1., 0.],
        [0., 1., 0., 1.]]))